spring.profiles.active=local
spring.application.name=sale
spring.jackson.default-property-inclusion=non_null

jwt.secret=tadneitsalesjavaproject2025tottemostrongsecret
jwt.expired=7200000

server.error.include-message=always
server.servlet.context-path=/api/s/
server.port=7077