spring.profiles.active=local
spring.application.name=sale
spring.jackson.default-property-inclusion=non_null

jwt.secret=tadneitsalesjavaproject2025tottemostrongsecret
jwt.expired=7200000

server.error.include-message=always
server.servlet.context-path=/api/s/
server.port=7077

spring.jpa.hibernate.ddl-auto=update

# Firebase Configuration
firebase.config.path=firebase/firebase.json
firebase.storage.bucket=tadneit-sale-project.firebasestorage.app

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB